// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvOFslO64EuqyiYlt6ij3bg95v1PEw9Ow',
    appId: '1:8967763541:web:ecdf2a96f27f2e212d86dc',
    messagingSenderId: '8967763541',
    projectId: 'max4u-65b09',
    authDomain: 'max4u-65b09.firebaseapp.com',
    storageBucket: 'max4u-65b09.appspot.com',
    measurementId: 'G-PLBL0B7FB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA46oQipmGDKu4iq6OI5Gg73pkznz-VO9E',
    appId: '1:8967763541:android:68b0eb4de10335512d86dc',
    messagingSenderId: '8967763541',
    projectId: 'max4u-65b09',
    storageBucket: 'max4u-65b09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmtbDWDOeoHSU6oqRd9Ma9qAj-wpMgxgY',
    appId: '1:8967763541:ios:716feda43b7137d02d86dc',
    messagingSenderId: '8967763541',
    projectId: 'max4u-65b09',
    storageBucket: 'max4u-65b09.appspot.com',
    iosBundleId: 'com.example.max4u',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmtbDWDOeoHSU6oqRd9Ma9qAj-wpMgxgY',
    appId: '1:8967763541:ios:716feda43b7137d02d86dc',
    messagingSenderId: '8967763541',
    projectId: 'max4u-65b09',
    storageBucket: 'max4u-65b09.appspot.com',
    iosBundleId: 'com.example.max4u',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvOFslO64EuqyiYlt6ij3bg95v1PEw9Ow',
    appId: '1:8967763541:web:25345b7ceb67693c2d86dc',
    messagingSenderId: '8967763541',
    projectId: 'max4u-65b09',
    authDomain: 'max4u-65b09.firebaseapp.com',
    storageBucket: 'max4u-65b09.appspot.com',
    measurementId: 'G-KG249J90M1',
  );
}
